version: '3.7'

services:

  testdb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /var/db/testdb:/var/lib/mysql
    ports:
      - 3306:3306

  testpma:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: testdb
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 8081:80